Add grid functionality
markwheeler/molly_the_poly pull request #1
Opened 2019-10-03 02:15 UTC by jaredpereira

Hi! This is a small PR to add grid_functionality. Most of the math was copied over from `earthsea`, and I did my best to reuse the functions already present in `molly_the_polly` and to follow the style.

Let me know if this is handy! Happy to iterate to get it to fit the code base :)

2019-10-17 22:45 UTC, markwheeler requested changes
Nice addition, thanks! I'm suggesting some changes for consistency and a little simplification regarding calculating the note number. Sorry it took me so long to look this over!

2019-10-17 22:45 UTC, markwheeler commented on molly_the_poly.lua
> +local g
```suggestion
local grid_device
```

2019-10-17 22:45 UTC, markwheeler commented on molly_the_poly.lua
> +end
Suggesting some renaming, no need to translate to freq and fixed note velocity (0-1 range):

```suggestion
local function grid_key(x, y, z)
  local note_num = util.clamp(((7 - y) * 5) + x + 33, 0, 127)
  
  if z == 1 then
    note_on(note_num, 0.8)
    grid_device:led(x, y, 15)
  else
    note_off(note_num)
    grid_device:led(x, y, 0)
  end
  grid_device:refresh()
end
```

2019-10-17 22:45 UTC, markwheeler commented on molly_the_poly.lua
> +  g = grid.connect()
```suggestion
  grid_device = grid.connect(1)
```

2019-10-17 22:45 UTC, markwheeler commented on molly_the_poly.lua
> +  g.key = grid_event
```suggestion
  grid_device.key = grid_key
```

2019-10-24 21:47 UTC, jaredpereira commented
Whoops! Sorry thought that your fixes were merged in automatically. Everything made sense to me, so merged em all in. Much shorter on calculating the note number,

2019-10-26 22:47 UTC, merged

2019-10-26 22:47 UTC, markwheeler commented
thank you!